targets:
  $default:
    builders:
      localized_text:
        enabled: true
        generate_for:
          exclude:
            - example
          include:
            - test/*
            - test/**/*
        options:
          format: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  localized_text:
    import: "package:localized_text/builder.dart"
    builder_factories: ["localized_text"]
    build_extensions: { ".dart": [".ltr.dart"] }
    auto_apply: dependents
    build_to: source