name: localized_text
description: >
  A package to generate simple API for localizations.
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ">=7.0.0 <8.0.0"
  build: ^2.3.1
  build_config: ^1.1.0
  collection: ^1.15.0
  meta: ^1.9.1
  source_gen: ^2.0.0
  localized_text_annotation:
    path: ../localized_text_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^2.1.5
  build_runner: ^2.3.3
  test: ^1.21.0
  matcher: ^0.12.14
  source_gen_test: ^1.0.6
  expect_error: ^1.0.8