// dart format width=80
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

part of 'fluent_ui.dart';

// **************************************************************************
// LocalizedTextGenerator
// **************************************************************************

class FluentR extends LocalizedTextGetter<FluentLocalizations> {
  static const localeName = FluentR._(0);
  static const backButtonTooltip = FluentR._(1);
  static const closeButtonLabel = FluentR._(2);
  static const searchLabel = FluentR._(3);
  static const closeNavigationTooltip = FluentR._(4);
  static const openNavigationTooltip = FluentR._(5);
  static const clickToSearch = FluentR._(6);
  static const modalBarrierDismissLabel = FluentR._(7);
  static const minimizeWindowTooltip = FluentR._(8);
  static const restoreWindowTooltip = FluentR._(9);
  static const closeWindowTooltip = FluentR._(10);
  static const dialogLabel = FluentR._(11);
  static const cutActionLabel = FluentR._(12);
  static const copyActionLabel = FluentR._(13);
  static const pasteActionLabel = FluentR._(14);
  static const selectAllActionLabel = FluentR._(15);
  static const undoActionLabel = FluentR._(16);
  static const newTabLabel = FluentR._(17);
  static const closeTabLabelSuffix = FluentR._(18);
  static const scrollTabBackwardLabel = FluentR._(19);
  static const scrollTabForwardLabel = FluentR._(20);
  static const noResultsFoundLabel = FluentR._(21);
  static const copyActionTooltip = FluentR._(22);
  static const cutActionTooltip = FluentR._(23);
  static const pasteActionTooltip = FluentR._(24);
  static const selectAllActionTooltip = FluentR._(25);
  static const undoActionTooltip = FluentR._(26);
  static const hour = FluentR._(27);
  static const minute = FluentR._(28);
  static const am = FluentR._(29);
  static const pm = FluentR._(30);
  static const month = FluentR._(31);
  static const day = FluentR._(32);
  static const year = FluentR._(33);
  static const seeMore = FluentR._(34);
  static const seeLess = FluentR._(35);
  static const redLabel = FluentR._(36);
  static const greenLabel = FluentR._(37);
  static const blueLabel = FluentR._(38);
  static const opacityLabel = FluentR._(39);
  static const hueLabel = FluentR._(40);
  static const saturationLabel = FluentR._(41);
  static const valueLabel = FluentR._(42);
  static const moreText = FluentR._(43);
  static const lessText = FluentR._(44);
  static const colorBlack = FluentR._(45);
  static const colorNavy = FluentR._(46);
  static const colorDarkBlue = FluentR._(47);
  static const colorMediumBlue = FluentR._(48);
  static const colorBlue = FluentR._(49);
  static const colorDarkGreen = FluentR._(50);
  static const colorGreen = FluentR._(51);
  static const colorTeal = FluentR._(52);
  static const colorDarkCyan = FluentR._(53);
  static const colorDeepSkyBlue = FluentR._(54);
  static const colorDarkTurquoise = FluentR._(55);
  static const colorMediumSpringGreen = FluentR._(56);
  static const colorLime = FluentR._(57);
  static const colorSpringGreen = FluentR._(58);
  static const colorCyan = FluentR._(59);
  static const colorMidnightBlue = FluentR._(60);
  static const colorDodgerBlue = FluentR._(61);
  static const colorLightSeaGreen = FluentR._(62);
  static const colorForestGreen = FluentR._(63);
  static const colorSeaGreen = FluentR._(64);
  static const colorDarkSlateGray = FluentR._(65);
  static const colorLimeGreen = FluentR._(66);
  static const colorMediumSeaGreen = FluentR._(67);
  static const colorTurquoise = FluentR._(68);
  static const colorRoyalBlue = FluentR._(69);
  static const colorSteelBlue = FluentR._(70);
  static const colorDarkSlateBlue = FluentR._(71);
  static const colorMediumTurquoise = FluentR._(72);
  static const colorIndigo = FluentR._(73);
  static const colorDarkOliveGreen = FluentR._(74);
  static const colorCadetBlue = FluentR._(75);
  static const colorCornflowerBlue = FluentR._(76);
  static const colorMediumAquamarine = FluentR._(77);
  static const colorDimGray = FluentR._(78);
  static const colorSlateBlue = FluentR._(79);
  static const colorOliveDrab = FluentR._(80);
  static const colorSlateGray = FluentR._(81);
  static const colorLightSlateGray = FluentR._(82);
  static const colorMediumSlateBlue = FluentR._(83);
  static const colorLawnGreen = FluentR._(84);
  static const colorChartreuse = FluentR._(85);
  static const colorAquamarine = FluentR._(86);
  static const colorMaroon = FluentR._(87);
  static const colorPurple = FluentR._(88);
  static const colorOlive = FluentR._(89);
  static const colorGray = FluentR._(90);
  static const colorSkyBlue = FluentR._(91);
  static const colorLightSkyBlue = FluentR._(92);
  static const colorBlueViolet = FluentR._(93);
  static const colorDarkRed = FluentR._(94);
  static const colorDarkMagenta = FluentR._(95);
  static const colorSaddleBrown = FluentR._(96);
  static const colorDarkSeaGreen = FluentR._(97);
  static const colorLightGreen = FluentR._(98);
  static const colorMediumPurple = FluentR._(99);
  static const colorDarkViolet = FluentR._(100);
  static const colorPaleGreen = FluentR._(101);
  static const colorDarkOrchid = FluentR._(102);
  static const colorYellowGreen = FluentR._(103);
  static const colorSienna = FluentR._(104);
  static const colorBrown = FluentR._(105);
  static const colorDarkGray = FluentR._(106);
  static const colorLightBlue = FluentR._(107);
  static const colorGreenYellow = FluentR._(108);
  static const colorPaleTurquoise = FluentR._(109);
  static const colorLightSteelBlue = FluentR._(110);
  static const colorPowderBlue = FluentR._(111);
  static const colorFirebrick = FluentR._(112);
  static const colorDarkGoldenrod = FluentR._(113);
  static const colorMediumOrchid = FluentR._(114);
  static const colorRosyBrown = FluentR._(115);
  static const colorDarkKhaki = FluentR._(116);
  static const colorSilver = FluentR._(117);
  static const colorMediumVioletRed = FluentR._(118);
  static const colorIndianRed = FluentR._(119);
  static const colorPeru = FluentR._(120);
  static const colorChocolate = FluentR._(121);
  static const colorTan = FluentR._(122);
  static const colorLightGray = FluentR._(123);
  static const colorThistle = FluentR._(124);
  static const colorOrchid = FluentR._(125);
  static const colorGoldenrod = FluentR._(126);
  static const colorPaleVioletRed = FluentR._(127);
  static const colorCrimson = FluentR._(128);
  static const colorGainsboro = FluentR._(129);
  static const colorPlum = FluentR._(130);
  static const colorBurlyWood = FluentR._(131);
  static const colorLightCyan = FluentR._(132);
  static const colorLavender = FluentR._(133);
  static const colorDarkSalmon = FluentR._(134);
  static const colorViolet = FluentR._(135);
  static const colorPaleGoldenrod = FluentR._(136);
  static const colorLightCoral = FluentR._(137);
  static const colorKhaki = FluentR._(138);
  static const colorAliceBlue = FluentR._(139);
  static const colorHoneydew = FluentR._(140);
  static const colorAzure = FluentR._(141);
  static const colorSandyBrown = FluentR._(142);
  static const colorWheat = FluentR._(143);
  static const colorBeige = FluentR._(144);
  static const colorWhiteSmoke = FluentR._(145);
  static const colorMintCream = FluentR._(146);
  static const colorGhostWhite = FluentR._(147);
  static const colorSalmon = FluentR._(148);
  static const colorAntiqueWhite = FluentR._(149);
  static const colorLinen = FluentR._(150);
  static const colorLightGoldenrodYellow = FluentR._(151);
  static const colorOldLace = FluentR._(152);
  static const colorRed = FluentR._(153);
  static const colorMagenta = FluentR._(154);
  static const colorDeepPink = FluentR._(155);
  static const colorOrangeRed = FluentR._(156);
  static const colorTomato = FluentR._(157);
  static const colorHotPink = FluentR._(158);
  static const colorCoral = FluentR._(159);
  static const colorDarkOrange = FluentR._(160);
  static const colorLightSalmon = FluentR._(161);
  static const colorOrange = FluentR._(162);
  static const colorLightPink = FluentR._(163);
  static const colorPink = FluentR._(164);
  static const colorGold = FluentR._(165);
  static const colorPeachPuff = FluentR._(166);
  static const colorNavajoWhite = FluentR._(167);
  static const colorMoccasin = FluentR._(168);
  static const colorBisque = FluentR._(169);
  static const colorMistyRose = FluentR._(170);
  static const colorBlanchedAlmond = FluentR._(171);
  static const colorPapayaWhip = FluentR._(172);
  static const colorLavenderBlush = FluentR._(173);
  static const colorSeaShell = FluentR._(174);
  static const colorCornsilk = FluentR._(175);
  static const colorLemonChiffon = FluentR._(176);
  static const colorFloralWhite = FluentR._(177);
  static const colorSnow = FluentR._(178);
  static const colorYellow = FluentR._(179);
  static const colorLightYellow = FluentR._(180);
  static const colorIvory = FluentR._(181);
  static const colorWhite = FluentR._(182);

  const FluentR._(this._$type) : _$arg0 = null, _$arg1 = null;

  const FluentR.valueSliderTooltip(int value, String colorName)
    : _$type = 183,
      _$arg0 = value,
      _$arg1 = colorName;
  const FluentR.alphaSliderTooltip(int value)
    : _$type = 184,
      _$arg0 = value,
      _$arg1 = null;

  final int _$type;
  final dynamic _$arg0;
  final dynamic _$arg1;

  @override
  String get(FluentLocalizations resource) {
    return getNullable(resource)!;
  }

  @override
  String? getNullable(FluentLocalizations resource) => switch (_$type) {
    0 => resource.localeName,
    1 => resource.backButtonTooltip,
    2 => resource.closeButtonLabel,
    3 => resource.searchLabel,
    4 => resource.closeNavigationTooltip,
    5 => resource.openNavigationTooltip,
    6 => resource.clickToSearch,
    7 => resource.modalBarrierDismissLabel,
    8 => resource.minimizeWindowTooltip,
    9 => resource.restoreWindowTooltip,
    10 => resource.closeWindowTooltip,
    11 => resource.dialogLabel,
    12 => resource.cutActionLabel,
    13 => resource.copyActionLabel,
    14 => resource.pasteActionLabel,
    15 => resource.selectAllActionLabel,
    16 => resource.undoActionLabel,
    17 => resource.newTabLabel,
    18 => resource.closeTabLabelSuffix,
    19 => resource.scrollTabBackwardLabel,
    20 => resource.scrollTabForwardLabel,
    21 => resource.noResultsFoundLabel,
    22 => resource.copyActionTooltip,
    23 => resource.cutActionTooltip,
    24 => resource.pasteActionTooltip,
    25 => resource.selectAllActionTooltip,
    26 => resource.undoActionTooltip,
    27 => resource.hour,
    28 => resource.minute,
    29 => resource.am,
    30 => resource.pm,
    31 => resource.month,
    32 => resource.day,
    33 => resource.year,
    34 => resource.seeMore,
    35 => resource.seeLess,
    36 => resource.redLabel,
    37 => resource.greenLabel,
    38 => resource.blueLabel,
    39 => resource.opacityLabel,
    40 => resource.hueLabel,
    41 => resource.saturationLabel,
    42 => resource.valueLabel,
    43 => resource.moreText,
    44 => resource.lessText,
    45 => resource.colorBlack,
    46 => resource.colorNavy,
    47 => resource.colorDarkBlue,
    48 => resource.colorMediumBlue,
    49 => resource.colorBlue,
    50 => resource.colorDarkGreen,
    51 => resource.colorGreen,
    52 => resource.colorTeal,
    53 => resource.colorDarkCyan,
    54 => resource.colorDeepSkyBlue,
    55 => resource.colorDarkTurquoise,
    56 => resource.colorMediumSpringGreen,
    57 => resource.colorLime,
    58 => resource.colorSpringGreen,
    59 => resource.colorCyan,
    60 => resource.colorMidnightBlue,
    61 => resource.colorDodgerBlue,
    62 => resource.colorLightSeaGreen,
    63 => resource.colorForestGreen,
    64 => resource.colorSeaGreen,
    65 => resource.colorDarkSlateGray,
    66 => resource.colorLimeGreen,
    67 => resource.colorMediumSeaGreen,
    68 => resource.colorTurquoise,
    69 => resource.colorRoyalBlue,
    70 => resource.colorSteelBlue,
    71 => resource.colorDarkSlateBlue,
    72 => resource.colorMediumTurquoise,
    73 => resource.colorIndigo,
    74 => resource.colorDarkOliveGreen,
    75 => resource.colorCadetBlue,
    76 => resource.colorCornflowerBlue,
    77 => resource.colorMediumAquamarine,
    78 => resource.colorDimGray,
    79 => resource.colorSlateBlue,
    80 => resource.colorOliveDrab,
    81 => resource.colorSlateGray,
    82 => resource.colorLightSlateGray,
    83 => resource.colorMediumSlateBlue,
    84 => resource.colorLawnGreen,
    85 => resource.colorChartreuse,
    86 => resource.colorAquamarine,
    87 => resource.colorMaroon,
    88 => resource.colorPurple,
    89 => resource.colorOlive,
    90 => resource.colorGray,
    91 => resource.colorSkyBlue,
    92 => resource.colorLightSkyBlue,
    93 => resource.colorBlueViolet,
    94 => resource.colorDarkRed,
    95 => resource.colorDarkMagenta,
    96 => resource.colorSaddleBrown,
    97 => resource.colorDarkSeaGreen,
    98 => resource.colorLightGreen,
    99 => resource.colorMediumPurple,
    100 => resource.colorDarkViolet,
    101 => resource.colorPaleGreen,
    102 => resource.colorDarkOrchid,
    103 => resource.colorYellowGreen,
    104 => resource.colorSienna,
    105 => resource.colorBrown,
    106 => resource.colorDarkGray,
    107 => resource.colorLightBlue,
    108 => resource.colorGreenYellow,
    109 => resource.colorPaleTurquoise,
    110 => resource.colorLightSteelBlue,
    111 => resource.colorPowderBlue,
    112 => resource.colorFirebrick,
    113 => resource.colorDarkGoldenrod,
    114 => resource.colorMediumOrchid,
    115 => resource.colorRosyBrown,
    116 => resource.colorDarkKhaki,
    117 => resource.colorSilver,
    118 => resource.colorMediumVioletRed,
    119 => resource.colorIndianRed,
    120 => resource.colorPeru,
    121 => resource.colorChocolate,
    122 => resource.colorTan,
    123 => resource.colorLightGray,
    124 => resource.colorThistle,
    125 => resource.colorOrchid,
    126 => resource.colorGoldenrod,
    127 => resource.colorPaleVioletRed,
    128 => resource.colorCrimson,
    129 => resource.colorGainsboro,
    130 => resource.colorPlum,
    131 => resource.colorBurlyWood,
    132 => resource.colorLightCyan,
    133 => resource.colorLavender,
    134 => resource.colorDarkSalmon,
    135 => resource.colorViolet,
    136 => resource.colorPaleGoldenrod,
    137 => resource.colorLightCoral,
    138 => resource.colorKhaki,
    139 => resource.colorAliceBlue,
    140 => resource.colorHoneydew,
    141 => resource.colorAzure,
    142 => resource.colorSandyBrown,
    143 => resource.colorWheat,
    144 => resource.colorBeige,
    145 => resource.colorWhiteSmoke,
    146 => resource.colorMintCream,
    147 => resource.colorGhostWhite,
    148 => resource.colorSalmon,
    149 => resource.colorAntiqueWhite,
    150 => resource.colorLinen,
    151 => resource.colorLightGoldenrodYellow,
    152 => resource.colorOldLace,
    153 => resource.colorRed,
    154 => resource.colorMagenta,
    155 => resource.colorDeepPink,
    156 => resource.colorOrangeRed,
    157 => resource.colorTomato,
    158 => resource.colorHotPink,
    159 => resource.colorCoral,
    160 => resource.colorDarkOrange,
    161 => resource.colorLightSalmon,
    162 => resource.colorOrange,
    163 => resource.colorLightPink,
    164 => resource.colorPink,
    165 => resource.colorGold,
    166 => resource.colorPeachPuff,
    167 => resource.colorNavajoWhite,
    168 => resource.colorMoccasin,
    169 => resource.colorBisque,
    170 => resource.colorMistyRose,
    171 => resource.colorBlanchedAlmond,
    172 => resource.colorPapayaWhip,
    173 => resource.colorLavenderBlush,
    174 => resource.colorSeaShell,
    175 => resource.colorCornsilk,
    176 => resource.colorLemonChiffon,
    177 => resource.colorFloralWhite,
    178 => resource.colorSnow,
    179 => resource.colorYellow,
    180 => resource.colorLightYellow,
    181 => resource.colorIvory,
    182 => resource.colorWhite,
    183 => resource.valueSliderTooltip(_$arg0 as int, _$arg1 as String),
    184 => resource.alphaSliderTooltip(_$arg0 as int),
    _ =>
      throw UnimplementedError(
        '${_$type} is unimplemented. This is a error of localized_text builder.',
      ),
  };
}
